dbi - Add psql condition and some docs

diff --git a/.local/bin/work/dbi b/.local/bin/work/dbi
--- a/.local/bin/work/dbi
+++ b/.local/bin/work/dbi
@@ -1,10 +1,15 @@
 #!/usr/bin/bash
 
-set -e
-set -m
+set -e # Exit the script on error
+set -m # Run all jobs in their own process group
 
 if ! type "python" > /dev/null; then
     echo "This script requires python"
+    exit 1
+fi
+
+if ! type "psql" > /dev/null; then
+    echo "This script requires psql"
     exit 1
 fi
 
